name: Build Docker Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and Push Docker Image
        run: ./push-container.sh ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
